/control/verbose 2
/vis/open OGL 600x600-0+0
#/vis/drawVolume
/vis/viewer/reset


# Create a new empty scene and attach it to handler
/vis/scene/create

# Add world volume, trajectories and hits to the scene
/vis/scene/add/volume
/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/sceneHandler/attach

/vis/viewer/set/style wireframe
/vis/viewer/set/projection perspective 50 deg

/control/alias phi 30
/control/loop movie.loop theta 0 360 5
